name: safedrive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  geocoding: ^2.1.0
  image_picker: ^1.0.2
  flutter_image_compress: ^2.1.0
  path_provider: ^2.0.11
  path: ^1.8.3
  http: ^0.13.6
  flutter_polyline_points: ^1.0.0
  provider: ^6.1.5
  cloud_firestore: ^5.6.8
  uuid: ^4.5.1
  firebase_storage: ^12.4.6
  cached_network_image: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Safedrive.png
    - assets/images/skytowers.png
    - assets/images/onboardinglocation.png
    - assets/images/onboardingalert.png
    - assets/images/safedrive_black.png
    - assets/images/flag_mz.png
    - assets/images/roadblock.png
