// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAs_rC0ItHjZ5CixukZtr8tZ5rAqOZct8',
    appId: '1:360791376391:web:dea3fee461643a5834a0a2',
    messagingSenderId: '360791376391',
    projectId: 'safedrive-2025',
    authDomain: 'safedrive-2025.firebaseapp.com',
    storageBucket: 'safedrive-2025.firebasestorage.app',
    measurementId: 'G-WVCD5T1Y32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyY85P1PJOQm2dK5EwPBtlWbk9YDSgBQ4',
    appId: '1:360791376391:android:8efd7577c6f3fb6734a0a2',
    messagingSenderId: '360791376391',
    projectId: 'safedrive-2025',
    storageBucket: 'safedrive-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMH4q5p4veO7zG1jNeyWOVOpsLn9Prtjg',
    appId: '1:360791376391:ios:85d0d099480f7f2434a0a2',
    messagingSenderId: '360791376391',
    projectId: 'safedrive-2025',
    storageBucket: 'safedrive-2025.firebasestorage.app',
    iosBundleId: 'com.example.safedrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMH4q5p4veO7zG1jNeyWOVOpsLn9Prtjg',
    appId: '1:360791376391:ios:85d0d099480f7f2434a0a2',
    messagingSenderId: '360791376391',
    projectId: 'safedrive-2025',
    storageBucket: 'safedrive-2025.firebasestorage.app',
    iosBundleId: 'com.example.safedrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAs_rC0ItHjZ5CixukZtr8tZ5rAqOZct8',
    appId: '1:360791376391:web:ba53642d49fe253634a0a2',
    messagingSenderId: '360791376391',
    projectId: 'safedrive-2025',
    authDomain: 'safedrive-2025.firebaseapp.com',
    storageBucket: 'safedrive-2025.firebasestorage.app',
    measurementId: 'G-QPR0NJMN72',
  );
}
